import Header from "./components/Header";
import "./globals.css";
import { Inter, Paytone_One } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const paytone_One = Paytone_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={paytone_One.className}>{children}</body>
    </html>
  );
}
